development:
  adapter: postgresql
  database: moving_bro_development
  encoding: unicode
  user: moving_bro
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: moving_bro_test
  encoding: unicode
  user: moving_bro
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: moving_bro_production
  encoding: unicode
  pool: 5
  timeout: 5000